// Code generated by font/vector/convert.go; DO NOT EDIT.
package constant

import (
	_ "embed"
	"github.com/mineracks/seedhammer-v1-companion/font/vector"
	"unsafe"
)

var Font = vector.NewFace(unsafe.Slice(unsafe.StringData(constantData), len(constantData)))

//go:embed constant.bin
var constantData string
