// Code generated by font/bitmap/convert.go; DO NOT EDIT.

package poppins

import (
	_ "embed"
	"github.com/mineracks/seedhammer-v1-companion/font/bitmap"
	"unsafe"
)

var Bold10 = bitmap.NewFace(unsafe.Slice(unsafe.StringData(databold10), len(databold10)))

//go:embed bold10.bin
var databold10 string
