// Code generated by font/bitmap/convert.go; DO NOT EDIT.

package comfortaa

import (
	_ "embed"
	"github.com/mineracks/seedhammer-v1-companion/font/bitmap"
	"unsafe"
)

var Bold17 = bitmap.NewFace(unsafe.Slice(unsafe.StringData(databold17), len(databold17)))

//go:embed bold17.bin
var databold17 string
