// Code generated by font/bitmap/convert.go; DO NOT EDIT.

package comfortaa

import (
	_ "embed"
	"github.com/mineracks/seedhammer-v1-companion/font/bitmap"
	"unsafe"
)

var Regular16 = bitmap.NewFace(unsafe.Slice(unsafe.StringData(dataregular16), len(dataregular16)))

//go:embed regular16.bin
var dataregular16 string
